name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [ '1.20' ]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Go
        uses: actions/setup-go@v3


      - name: Build
        run: go build -v ./...
      
      - name: Test
        run: go test -v ./...
